### ISSUE TITLE
Is it possible with your geocoder where I can use a predefined location from a database and find the Lat & Long using your plugin?

### ISSUE THREAD

**Issue by samauto** [2amigos/yii2-leaflet-geocoder-plugin#1]
Is it possible with your geocoder where I can use a predefined location from a database and find the Lat & Long using your plugin?

**Comment by tonydspaniard** [comment]
This plugin is attached to the leaflet map and using one of the reverse geo providers. This is not a reverse geo coder tool from address locations on your database. 

For that I highly recommend the following library: https://github.com/geocoder-php/Geocoder 

That library would help you doing that.
