### ISSUE TITLE
yii\base\ErrorException: Cannot use yii\base\Object as Object because 'Object' is a special class name 

### ISSUE THREAD

**Issue by joetwostep** [2amigos/yii2-leaflet-geocoder-plugin#4]
In file BaseService.php I needed to update Object to BaseObject for the newest version of Yii2.

**Comment by 4khobta** [comment]
Not updated commit with "BaseObject" via composer (

**Comment by tonydspaniard** [comment]
I'll do my best to fix it asap... apologies for the delay

**Comment by vdstud** [comment]
Hello. I fixed it like [this](https://github.com/unclead/yii2-multiple-input/commit/dfeb61549c90814db35d0fb80b15ac28117efba4).

**Comment by tonydspaniard** [comment]
Fixing it

**Comment by tonydspaniard** [comment]
Fixed on tag 1.0.3
